First commit Индикаторы
dasdias/webdev-team01 pull request #16
Opened 2018-12-03 10:07 UTC by IrinaZhuravleva

2018-12-03 10:18 UTC, nobleworkshop commented on src/less/blocks/_indicators.less
> +	width: 1600px;
Зачем такая ширина? Почему не 100%?

2018-12-03 10:19 UTC, nobleworkshop commented on src/less/blocks/_indicators.less
> +	height: 660px;
Как мы делаем высоту? Правильно, если можно, то по высоте контента. Не забудьте добавить паддинги для отступов сверху и снизу.

2018-12-03 10:21 UTC, nobleworkshop commented on src/pug/pages/ui/indicators.pug
> +						.pl-60
Уберите все подобные пустые дивы .pl-60
Надо сверстать чтобы не было таких пустых элементов. Когда это исключение - еще ок. Но в данном случае, похоже что это уже правило. Надо стараться избегать таких решений.

2018-12-03 10:21 UTC, nobleworkshop requested changes
Хорошо!) Пару моментов:

1) В документации, Индикаторы - это скорее "Секция", а не "Элементы форм".
2) Сделайте несколько индикаторов с разным значением, 40, 50, 90%.
3) Добавьте пример подключения секции в документации.

Еще оставил комментарии в коде.

2018-12-03 15:24 UTC, nobleworkshop requested changes
Уберите правый отступ от последнего в ряду индикатора, и так у каждого ряда. https://yadi.sk/i/tvyC3rxTPmfmeQ

2018-12-05 20:27 UTC, dasdias requested changes
1. Отступ от края до индикаторов должен быть 98px округляем до 100px.
https://yadi.sk/i/3oOPI4UOYNsP-A
2 Атрибут viewbox разместите в теге svg, в css оно не работает.
https://yadi.sk/i/S6TH5icpauaIIg

2018-12-06 08:00 UTC, dasdias requested changes
Здравствуйте, Ирина! Вы не правильно задали ширину и высоту svg иконки. В макете она равна 112px
https://yadi.sk/i/YakKuECG75kx3A Соответственно изменятся размеры viewbox, cx, cy и радиус.

2018-12-06 08:11 UTC, dasdias requested changes

2018-12-06 08:11 UTC, dasdias commented on src/less/blocks/_indicators.less
> +	font-weight: 700;
По макету font-weight: 900;

2018-12-07 07:47 UTC, IrinaZhuravleva commented on src/less/blocks/_indicators.less
> +	width: 125px;
Я задала окошко побольше. Но если вы считаете, что оно должно равняться диаметру circle, то я изменю.

2018-12-07 08:06 UTC, IrinaZhuravleva commented on src/less/blocks/_indicators.less
> +	font-weight: 700;
Сделано

2018-12-07 08:06 UTC, IrinaZhuravleva commented on src/less/blocks/_indicators.less
> +	width: 125px;
Сделано.

2018-12-07 08:34 UTC, IrinaZhuravleva commented on src/less/blocks/_indicators.less
> +	width: 125px;
Оставлено как есть 125px до выяснений, каким должен быть периметр. При высоте 112 или 122 круг частично скрывается за рамками вьюбокса.

2018-12-07 10:25 UTC, dasdias requested changes
Задайте атрибут viewbox

2018-12-07 18:06 UTC, dasdias approved these changes
Все хорошо! Можно мержить.

2018-12-07 19:47 UTC, merged