Typography
dasdias/webdev-team01 pull request #3
Opened 2018-11-28 12:44 UTC by DmitriiTokar

2018-11-28 21:10 UTC, dasdias requested changes
1. Нужны правки. В теге h6 допущена ошибка, неправильно закрыта скобка.
2. В ui-kit не описаны параграф с ссылками и списки.

2018-11-29 06:39 UTC, DmitriiTokar commented
Поправил h6. По абзацам в UI-KIT отдельные страницы, на которых все описано

2018-11-29 07:46 UTC, dasdias commented
Здравствуйте Дмитрий! В Типографике при описании ссылок в теге pre используйте вот такую конструкцию #{'#[a(href="#!") Сьерра-Невада]'} Тогда в теге pre будет видно как вызывается ссылка в тексте. После правки, можно мержить.

2018-11-29 07:47 UTC, dasdias approved these changes

2018-11-29 07:51 UTC, DmitriiTokar commented
Исправлено!

2018-11-29 07:52 UTC, merged