pageBlog
dasdias/webdev-team01 pull request #33
Opened 2018-12-07 09:57 UTC by DmitriiTokar

Готово для первой проверки

2018-12-07 18:59 UTC, dasdias requested changes
1. У заголовка font-weight должен быть 900
2. Картинки в карточках не отображаются. https://yadi.sk/i/0IVSiDKf3WpMjA
3. В первом ряду, первая карточка и последний ряд первая карточка, поменяйте текст.

2018-12-09 15:18 UTC, DmitriiTokar commented
исправлено

2018-12-09 16:52 UTC, dasdias requested changes
1.  Картинка в карточке не соответствует макету
первый ряд. первая карточка
второй ряд последняя какрточка
третий ряд первая карточка

2018-12-10 08:13 UTC, dasdias approved these changes
Все хорошо. Можно мержить.

2018-12-10 08:26 UTC, merged