состряпал секцию Загрузка файлов
dasdias/webdev-team01 pull request #35
Opened 2018-12-07 18:10 UTC by palekov

2018-12-07 19:52 UTC, dasdias requested changes
1. У заголовка font-weight должен быть 900, font-size должен быть 16. отступ вниз 15px
2. У дива с классом load-file-fieldset уберите паддинги и margin-bottom: 30px;
3. Хорошо было бы если текст в заголовок и в описание, можно было передавать через миксин.

2018-12-08 19:11 UTC, palekov commented
Внёс исправления, добавил второй вариант кнопки, сделал через миксин.

2018-12-08 23:16 UTC, dasdias requested changes
1. Опишите в документации для каждой кнопки, как вызвать миксин. Какие параметры нужно в них передавать.
2. Уберите тег br из разметки. Используйте стили css.
3. Скрипт передавайте в футер конструкцией block append scripts
4. Миксины мы подключаем в файде pug/layouts/_mixins-links.pug
5. Уберите лишние классы и стили которые вы не используете.
6. sections/load-file.pug лишний файл. Вызов миксина описывайте в документации pages/ui/load-file.pug Подключение скрипта поместите в миксин от туда передавайте его в футер, следующей конструкцией:
```
block append scripts
	script(src='../../js/custom-file-input.js')

```
Если что-то непонятно, пишите в Slack

2018-12-09 13:07 UTC, palekov commented
Исправил согласно замечаний. Блин забыл удалить ненужный файл.

2018-12-09 16:33 UTC, dasdias requested changes
Александр, здравствуйте!
Давайте все-таки уберем подключение скрипта из миксина и запишем его сразу в pug/layouts/page-layout/_foot.pug Добавьте его в block scripts . Пусть этот скрипт будет подключен на всех страницах

2018-12-10 16:53 UTC, palekov commented
исправил

2018-12-10 17:09 UTC, palekov commented
прописал в документации, что подключили скрипт custom-file-input.js

2018-12-10 18:02 UTC, dasdias requested changes
1. div с классом load-file-title должен иметь:
 font-weight: 700;
color: 222222;
2. div с классом load-file-opis:
color: 222222;
3. .inputfile + label + span должен иметь:
 color: #8e9ba2; font-weight: 400;
4. load-file-fieldset уберите отступ margin-bottom: 25px; Он будет задаваться на странице сборки.
Когда отступ уберёте, в документации миксины разделите классом .section-ui , чтобы хорошо смотрелось.

2018-12-10 18:31 UTC, palekov commented
подправил

2018-12-10 18:41 UTC, dasdias approved these changes
Хорошо. Можно мержить.

2018-12-10 18:45 UTC, merged