first commit
dasdias/webdev-team01 pull request #57
Opened 2018-12-11 18:09 UTC by palekov

Перенёс в Элементы форм. Добавил подсказку Файл не выбран.

2018-12-11 19:39 UTC, dasdias approved these changes
Всё хорошо! Можно мержить.

2018-12-12 08:43 UTC, dasdias requested changes
У кнопки со скруглёнными краями нужно изменить раддинги на
padding: 14px 20.2px;

2018-12-12 18:26 UTC, palekov commented
исправлено

2018-12-12 18:33 UTC, dasdias approved these changes
Ок, Можно мержить.

2018-12-12 18:36 UTC, merged