header-guest
dasdias/webdev-team01 pull request #9
Opened 2018-11-30 13:02 UTC by DmitriiTokar

Сделал шапку. Вариант без кнопок. Как закончат с кнопками - продолжу. Какраз после этого мержа

2018-11-30 21:21 UTC, dasdias commented
1. Общая высота шапки  должна быть 200px
2. Эффект по ховеру у ссылок регистрация и вход должен быть такой же как у меню.

2018-11-30 21:26 UTC, dasdias requested changes
1. Общая высота шапки должна быть 200px
2. Эффект по ховеру у ссылок регистрация и вход должен быть такой же как у меню.
3. В меню у последнего тега li уберите отступ.

2018-12-01 09:53 UTC, DmitriiTokar commented
Исправлено!

2018-12-01 14:56 UTC, nobleworkshop requested changes
Хорошо!) Есть еще моменты для правки.

1) Весь код шапки должен быть вынесен в отдельную секцию и подключен оттуда.

2) Вижу сверстан логотип, но не оформлен ни в миксин ни в секцию. Надо оформить и подключать его уже оттуда.

3) В левой навигации - Шапка это секция, а не блок. Надо перенести в другой раздел. А вот Логотип и Вход - блоки. Навигация - тоже ближе к блоку. Блок - единый смысловой элемент.  Секция - состоит из нескольких блоков.

2018-12-01 14:56 UTC, nobleworkshop commented on src/pug/pages/ui/header-guest.pug
> +                div
Зачем пустой div? Дайте ему класс, чтобы обозначить что он тут не просто так.

2018-12-01 14:56 UTC, nobleworkshop commented on src/pug/pages/ui/header-guest.pug
> +                        div.logo-icon
Давайте напишем по БЭМ неймингу.

2018-12-01 14:56 UTC, nobleworkshop commented on src/pug/mixins/_sign-in-guest.pug
> +mixin sign-in-guest(registerLink, signInLink)
Смысл в этом миксине, если все что он принимает только ссылки, а контент в нем и так всегда один. Лучше оформить этот блок секцией.

2018-12-01 14:56 UTC, nobleworkshop commented on src/less/sections/_sign-in-guest.less
> +    color: @white;
Лучше чтобы этот блок принимал цвет текста от родителя. Давайте поправим.

2018-12-03 12:31 UTC, DmitriiTokar commented
Исправлено!

2018-12-03 15:27 UTC, nobleworkshop requested changes
Сейчас шапка выглядит вот так: 
![image](https://user-images.githubusercontent.com/12967597/49383080-0090a780-f729-11e8-8608-f3a15a996de9.png)

Это не так как в макете.

2018-12-03 15:42 UTC, DmitriiTokar commented
Мне тим-лидер написал оставить пустую правую часть. Кого мне все-таки слушать?

2018-12-03 15:57 UTC, nobleworkshop requested changes
У вас все было неплохо, но вы ушли куда-то в сторону. Ориентируйтесь на те правки которые написаны в ПР-е.

Когда получаете правки стоит анализировать их. 

Надо сверстать эту секцию. Сейчас она выглядит вот так:
![image](https://user-images.githubusercontent.com/12967597/49384908-1e600b80-f72d-11e8-85ed-4781729f805f.png)

Шапка это секция. Не миксин. Которая состоит из верстки, и вложенных в нее секций (лого, навигация, кнопки входа или блок с bayj о пользователе)

Сами как думаете что надо поправить?

2018-12-03 17:03 UTC, DmitriiTokar commented
Сверстать лого и вход секциями и подключить. Навигацию оставить в миксинах может?

2018-12-04 07:16 UTC, DmitriiTokar commented
Сделал два варианта шапки секциями, которая включает другие секции лого, навигация и т.д.

2018-12-04 07:17 UTC, DmitriiTokar commented
Третий вариант будет сделан как будут кнопки

2018-12-04 11:51 UTC, DmitriiTokar commented
Изменения внесены

2018-12-04 15:55 UTC, dasdias requested changes
Здравствуйте, Дмитрий! Очень хорошая работа, Нужны небольшие правки.
1. https://yadi.sk/i/OdRWpRl5vTJUZA поправьте title
2. В макете, в логотипе иконка шрифтовая, у вас сделано через тег img (не знаю насколько это важно, но выполнено не по макету, поэтому на всякий случай пишу об этом)
3. https://yadi.sk/i/BkTvktZ5gQlTCQ замените аватарку, нужная иконка аватарки есть в проекте в папке img/avatars/avatar-admin.png

2018-12-05 06:42 UTC, DmitriiTokar commented
Исправлено! Думал png иконка в лого не так критично. При замене лого можно будет и иконку менять

2018-12-05 08:03 UTC, dasdias approved these changes
Все хорошо, можно мержить.

2018-12-05 08:34 UTC, merged